name: Sync Dev with Main

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
    branches: [main]

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Sync dev with main
      run: |
        git checkout main
        git pull origin main
        git checkout dev
        git rebase main
        git push origin dev --force-with-lease
        
    - name: Sync Success
      run: |
        echo "✅ Dev branch successfully synced with main"
        echo "🔄 Dev branch is now up-to-date after production deployment"